
name: Go Build Status
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Go Setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
      - name: Installing dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: testing 

        run: go test ./...

